import { createFileRoute } from '@tanstack/react-router';
import { Download, FileText } from 'lucide-react';
import { useState, type FormEvent } from 'react';
import { Site } from '@/components/site';
import { Button } from '@/components/ui/button';
import { products, pageHead } from '@/lib/products';

export const Route = createFileRoute('/contact')({ validateSearch: (search: Record<string, unknown>) => ({ product: typeof search.product === 'string' && products.some(p => p.id === search.product) ? search.product : '' }), head: () => pageHead('Request a quote', 'Prepare your stone, blocks, slabs, or polishing product requirements for a quotation from Australian Mining & Manufacturing.'), component: Contact });
function Contact() {
 const { product } = Route.useSearch();
 const [prepared, setPrepared] = useState(false);
 function submit(event: FormEvent<HTMLFormElement>) {
  event.preventDefault();
  const data = new FormData(event.currentTarget);
  const text = 'Australian Mining & Manufacturing — Product enquiry\n\n' + Array.from(data.entries()).map(([key,value]) => `${key}: ${value}`).join('\n');
  const url = URL.createObjectURL(new Blob([text], {type:'text/plain'}));
  const link = document.createElement('a'); link.href = url; link.download = 'stone-product-enquiry.txt'; link.click(); URL.revokeObjectURL(url); setPrepared(true);
 }
 return <Site><section className="section"><div className="site-container"><p className="eyebrow mb-5">LET’S TALK MATERIALS</p><h1 className="section-title text-4xl md:text-5xl">Request a quote</h1><p className="mt-5 max-w-2xl leading-7 text-muted-foreground">Start with the product you need. Include your material preferences, dimensions, finish, quantity, and project location.</p><div className="mt-12 grid gap-12 md:grid-cols-[1fr_1.5fr]"><aside><h2 className="text-2xl font-medium">Your requirements.<br />All in one place.</h2><div className="mt-7 flex gap-4 border-y border-border py-6"><FileText className="mt-1 size-5 shrink-0 text-primary" /><p className="text-sm leading-7 text-muted-foreground">Online enquiry delivery is not yet available. You can prepare and download your requirements below; nothing will be sent.</p></div><p className="mt-6 text-sm leading-7 text-muted-foreground">Business contact details will be added once confirmed.</p></aside><form onSubmit={submit} onChange={() => setPrepared(false)} className="space-y-6"><div className="grid gap-6 sm:grid-cols-2"><label className="text-sm font-medium">Full name *<input name="Full name" required autoComplete="name" className="form-field" /></label><label className="text-sm font-medium">Email address *<input type="email" name="Email" required autoComplete="email" className="form-field" /></label><label className="text-sm font-medium">Company<input name="Company" autoComplete="organization" className="form-field" /></label><label className="text-sm font-medium">Phone<input type="tel" name="Phone" autoComplete="tel" className="form-field" /></label></div><label className="block text-sm font-medium">Product category *<select key={product} name="Product" required defaultValue={product} className="form-field"><option value="" disabled>Select a product</option>{products.map(p => <option value={p.id} key={p.id}>{p.name}</option>)}<option value="general">General enquiry</option></select></label><label className="block text-sm font-medium">Project / delivery location<input name="Location" className="form-field" /></label><label className="block text-sm font-medium">Your requirements *<textarea name="Requirements" required maxLength={3000} rows={5} className="form-field" placeholder="Material, dimensions, thickness, finish, and quantity…" /><span className="mt-2 block text-xs font-normal text-muted-foreground">Maximum 3,000 characters.</span></label><p className="text-xs leading-6 text-muted-foreground">Your details stay in your browser until you download them. No enquiry is submitted or stored by this website.</p><Button type="submit" size="lg"><Download />Download enquiry</Button>{prepared && <div role="status" className="border-l-2 border-primary bg-secondary/30 p-4 text-sm leading-6">Your enquiry file is ready. It has not been sent to the company.</div>}</form></div></div></section></Site>;
}