import { createFileRoute, Link } from '@tanstack/react-router';
import { ArrowUpRight } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Site, QuoteBand } from '@/components/site';
import { products, pageHead } from '@/lib/products';

export const Route = createFileRoute('/products')({ validateSearch: (search: Record<string, unknown>): { category?: string } => ({ category: typeof search['category'] === 'string' && products.some(p => p.id === search['category']) ? search['category'] : 'all' }), head: () => pageHead('Our products', 'Explore natural stone, blocks, slabs, and polishing products from Australian Mining & Manufacturing.'), component: Products });
function Products() {
 const { category } = Route.useSearch();
 const shown = !category || category === 'all' ? products : products.filter(p => p.id === category);
 return <Site><section className="section border-b border-border"><div className="site-container"><p className="eyebrow mb-5">THE MATERIAL. THE FOUNDATION. THE FINISH.</p><h1 className="section-title text-4xl md:text-5xl">Our products</h1><p className="mt-5 max-w-2xl text-muted-foreground leading-7">Natural stone, blocks, slabs, and polishing products. Explore the categories and share your specifications for availability and a quotation.</p></div></section><section className="section"><div className="site-container"><nav aria-label="Product categories" className="mb-10 flex flex-wrap gap-2">{[{id:'all',name:'All products'},...products].map(p => <Button key={p.id} asChild variant={category === p.id ? 'default' : 'outline'}><Link to="/products" search={{ category: p.id }}>{p.name}</Link></Button>)}</nav><div className="grid gap-10 md:grid-cols-2">{shown.map(p => <article key={p.id} className="border-b border-border pb-8"><img src={p.image} alt={`${p.name} — representative category imagery`} width={768} height={512} className="aspect-[1.6] w-full rounded-sm object-cover" loading="lazy" /><p className="eyebrow mt-6">{p.tag}</p><h2 className="mt-3 text-2xl font-semibold">{p.name}</h2><p className="mt-3 text-sm leading-7 text-muted-foreground">{p.description} {p.detail}</p><Button asChild variant="link" className="mt-4 px-0"><Link to="/contact" search={{ product: p.id }}>Enquire about {p.name.toLowerCase()} <ArrowUpRight /></Link></Button></article>)}</div><p className="mt-10 text-xs text-muted-foreground">Images illustrate product categories, not confirmed stock. Material types, sizes, finishes, and availability are subject to enquiry.</p></div></section><QuoteBand /></Site>;
}